name: .NET Core

on:
  push:
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: dotnet restore   
       
    - name: Registry GitHub Source
      run : dotnet nuget add source https://nuget.pkg.github.com/jhonvedo/index.json -n github -u jhonvedo -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    
    - name: Build Nuget Package
      run: dotnet pack --configuration Release --no-restore 
      
    - name: Publish GitHub Package
      run: dotnet nuget push **/*.nupkg --source "github"
      
    - name: Publish Nuget Package
      run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --no-symbols true